create table Student(
                        id int primary key generated by default as identity ,
                        name varchar(100) not null ,
                        email varchar(200) not null unique ,
                        password varchar(200) not null,
                        date_of_birth varchar(20) not null
)